# SPDX-FileCopyrightText: 2022 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.priorityClass.enabled }}
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .Values.priorityClass.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
value: {{ required ".Values.priorityClass.value is required" .Values.priorityClass.value }}
globalDefault: false
description: "Priority class for the Gardener extension: {{ .Values.name }}."
{{- end }}
