# SPDX-FileCopyrightText: 2022 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v2
appVersion: "0.1.0"
description: A Helm chart for the Lakom admission controller.
name: lakom
version: 0.1.0
